### ISSUE TITLE
write microphone stream to .wav file

### ISSUE THREAD

**Issue by mcfiredrill** [saebekassebil/microphone-stream#9] opened 2016-11-24 12:57 UTC
Hi I’m trying to use this library to capture mic input then write it to a .wav file. I’m using electron, not sure if that’s relevant or not.

Everything seems to be working, but when I check out the exported wav file its all 0 bytes.

Inserting a debugger on this line, I see that `new Buffer(e.getInputChannel(0))` seems to return all 0s. 
https://github.com/saebekassebil/microphone-stream/blob/master/microphone-stream.js#L46
![screenshot 2016-11-24 21 47 54](https://cloud.githubusercontent.com/assets/66243/20599095/b8e43b48-b28f-11e6-8496-2e8a427fd95c.png)

e.getInputChannel(0) has non-zero data in it though, so I assume that is actually capturing mic input.
![screenshot 2016-11-24 21 47 24](https://cloud.githubusercontent.com/assets/66243/20599101/bf3a08e2-b28f-11e6-8647-8fbfe9671388.png)

Here is my code:
```
var MicrophoneStream = require('microphone-stream');
var wav = require('wav');
var process = require('process');

var fileWriter = new wav.FileWriter('demo.wav', {
  channels: 1,
  sampleRate: 44100,
  bitDepth: 16
});

var streaming = false;

var Streamer = function(stream) {
  var micStream = new MicrophoneStream(stream);

  this.connect = function(){

    micStream.pipe(process.stdout.pipe(fileWriter));

    micStream.on('format', function(format) {
      console.log(format);
    });

    streaming = true;
  }

  this.stop = function(){
    if (!streaming) return;
    streaming = false;
    if(fileWriter != null){
      fileWriter.end();
    }
    micStream.stop();
  }
}

module.exports = Streamer;
```

Do I misunderstand the concept of this library or something? I admit I am a bit new to the `Buffer` API, but if I understand correctly it is similar to a UInt8 array? Wouldn't this lose data somehow as it is a smaller type?

If you could help me understand exactly what is going on I would be really grateful!

**Comment by nfriedly** [comment] 2016-11-24 19:24
Op, this could be due to the deprecation of `new Buffer()` - https://nodejs.org/api/buffer.html#buffer_new_buffer_array

Can you try changing that line to 

    self.push(opts.objectMode ? e.inputBuffer : Buffer.from(e.inputBuffer.getChannelData(0)));

 in your copy of the lib and let me know if it behaves differently?

**Comment by nfriedly** [comment] 2016-11-24 19:44
One other thing to mention: while I believe the .wav format is capable of storing the 32-bit floats that the WebAudio API produces, most .wav files use 16-bit integers, and some audio players are not capable of decoding 32-bit float ones.  

The watson-speech library has a stream that can convert it to 16-bit little endian integers. It also downsamples from WebAudio's 48khz to 16khz by default, but you can disable that part.

Here's a rough example: 

```js
var WebAudioL16Stream = require('watson-speech/speech-to-text/webaudio-l16-stream.js');

//...

// wait until format event to set up pipes, because we need to know the sampleRate
// micStream.pipe(process.stdout.pipe(fileWriter));

micStream.on('format', function(format) {
  console.log(format);
  var l16Stream = new WebAudioL16Stream({
    sourceSampleRate: format.sampleRate,
    downsample: false, // set to true for 16khz (results in ~1/3 file size - useful for streaming). Be sure to update the format passed to wav.FileWriter if you do
    objectMode: false // this should match micStream's objectMode flag. True allows it to auto-detect the sourceSampleRate value.
  });
  // note: you may also want to create the wav.FileWriter() instance here and just pass it the `format` object directly.
  micStream.pipe(l16Stream)
    .pipe(process.stdout)
    .pipe(fileWriter));
});

//...
```

I haven't tested this, but you can see a known-working example at https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/speech-to-text/recognize-microphone.js

The watson-speech library uses microphone-stream, but in `objectMode`, so it didn't hit the `new Buffer()` issue (assuming that is the cause).


Oh, and if you're in the states, happy thanksgiving! 🦃

**Comment by mcfiredrill** [comment] 2016-11-25 09:13
@nfriedly 
Thanks alot for your detailed responses!
I've actually tried using Buffer.from instead, I also noticed that the use of `Buffer` was deprecated.
Unfortunately the behaviour is the same for me with this change.

I have also tried using the watson-speech library a bit after seeing this issue:
https://github.com/saebekassebil/microphone-stream/issues/8
I believe that also led to the same results.

I would try the example you constructed, but I also should note I am not getting the `format` event for whatever reason.

I am going to experiment with using `objectMode` to see if that makes any difference.

**Comment by mcfiredrill** [comment] 2016-12-05 02:59
@nfriedly so basically I never see that `format` event being emitted, do I have something configured incorrectly to where that would happen? 😰

**Comment by nfriedly** [comment] 2016-12-05 18:43
It fires [pretty early](https://github.com/saebekassebil/microphone-stream/blob/master/microphone-stream.js#L83) - it could be that the event fires before `this.connect()` is called (?)

**Comment by marcjoha** [comment] 2017-04-16 19:27
@mcfiredrill did you find a work-around for this? I'm seeing the same thing, and also haven't figured out how to use the Buffer without losing the float values. Couldn't get it to work with objectMode set to true either.

**Comment by mcfiredrill** [comment] 2017-04-17 02:19
@marcjoha it my case the format event was being fired before I was checking for it in my code, like @nfriedly said.

> It fires pretty early - it could be that the event fires before this.connect() is called (?)

**Comment by marcjoha** [comment] 2017-04-17 05:08
@mcfiredrill oh I meant the issue with Buffer(e.getInputChannel(0)) returning all zeroes

**Comment by mcfiredrill** [comment] 2017-04-17 05:35
@marcjoha I think the trick for me was to wait until the format event was fired, then I got data instead of all zeroes.

I also switched to using object mode. Sorry its hard to remember the exact details as this was a few months ago...

Here is part of the code I'm using now:

```
var Streamer = function(stream, config) {

  var micStream;
  var socket;
  var _this = this;

  this.connect = function(){
    micStream = new MicrophoneStream(stream, { objectMode: true });
    console.log(config);
    socket = net.connect({ host: config.host, port: Number(config.port) });
    socket.on('connect', function(){
      console.log("sending icecast headers...");
      _this.send_icecast_headers(socket);
    });
    socket.on('data', function(data){
      let decodedData = new TextDecoder("utf-8").decode(data);
      console.log(decodedData);
      if(decodedData === "HTTP/1.1 200 OK\r\n\r\n"){
        // start streaming!
        console.log("start streaming audio...");
        encoder.pipe(socket);
      }
      console.log(data);
    });

    micStream.on('format', function(format) {
      console.log(format);
      var l16Stream = new WebAudioL16Stream({
	sourceSampleRate: format.sampleRate,
	downsample: false, // set to true for 16khz (results in ~1/3 file size - useful for streaming). Be sure to update the format passed to wav.FileWriter if you do
	objectMode: true// this should match micStream's objectMode flag. True allows it to auto-detect the sourceSampleRate value.
      });
      // note: you may also want to create the wav.FileWriter() instance here and just pass it the `format` object directly.
      micStream.pipe(l16Stream)
	.pipe(encoder)
	.pipe(output);

    });
    streaming = true;
  }
```

**Comment by marcjoha** [comment] 2017-04-17 05:55
Thanks @mcfiredrill ! Changing to objectMode indeed bypasses the issue: https://github.com/saebekassebil/microphone-stream/blob/master/microphone-stream.js#L46

**Comment by nfriedly** [comment] 2017-04-17 13:44
Ok, it sounds like things are setteled here, I'm going to close this one.

**Closed as completed by nfriedly** 2017-04-17 13:44 UTC

**Comment by mcfiredrill** [comment] 2017-04-18 01:35
Sorry I didn't reply before, but your comments helped alot, thanks @nfriedly

**Comment by nfriedly** [comment] 2017-04-18 02:36
No worries, glad to hear it worked out @mcfiredrill :)
